### ISSUE TITLE
Save generated TTY audio to a .WAV file

### ISSUE THREAD

**Issue by davidnuon** [therealhttpsters/TDDEmulator#3]
A user will be able to save the output of a user's TTY message to a WAV file.

A good first place to look is `TTYOutput.java`. It contains a `Runnable` with all the logic for playing a TTY sequence. It an example of how to use the streaming API for audio. 

The intuition is that instead of writing to a `SourceDataLine` you'll instead write to a file.

**Comment by julioberina** [comment]
THIS IS COMING :taco: :taco: :tada: :beers:
